export enum AuthStatus {
  COMPLETED = 'COMPLETED',
  CHALLENGE = 'CHALLENGE',
}

export enum AuthChallengeType {
  MFA_TOTP = 'MFA_TOTP',
  MFA_BACKUP_CODE = 'MFA_BACKUP_CODE',
  MFA_EMAIL_OTP = 'MFA_EMAIL_OTP',
  MFA_ENROLL = 'MFA_ENROLL',
  DEVICE_VERIFY = 'DEVICE_VERIFY',
  MFA_REQUIRED = 'MFA_REQUIRED',
}

export enum AuthTxState {
  PASSWORD_VERIFIED = 'PASSWORD_VERIFIED',
  CHALLENGE_DEVICE_VERIFY = 'CHALLENGE_DEVICE_VERIFY',
  CHALLENGE_MFA_REQUIRED = 'CHALLENGE_MFA_REQUIRED',
  CHALLENGE_MFA_ENROLL = 'CHALLENGE_MFA_ENROLL',
}

export enum AuthMethod {
  EMAIL = 'email',
  TOTP = 'totp',
  BACKUP_CODE = 'backup-code',
}

export enum AuthNextStepKind {
  COMPLETE = 'COMPLETE',
  MFA_CHALLENGE = 'MFA_CHALLENGE',
  ENROLL_MFA = 'ENROLL_MFA',
  DEVICE_VERIFY = 'DEVICE_VERIFY',
}
