export enum ErrCode {
  InternalError = 'internal-error',
  NotFound = 'not-found',
  BadRequest = 'bad-request',
  ValidationError = 'validation-error',
  ItemNotFound = 'item-not-found',
  ItemExists = 'item-exists',
  PasswordNotMatch = 'password-not-match',
  PasswordExpired = 'password-expired',
  PasswordNotSet = 'password-not-set',
  PasswordMaxAttempt = 'password-max-attempt',
  UserNotFound = 'user-not-found',
  UserExisted = 'user-existed',
  UserNotActive = 'user-not-active',
  InvalidToken = 'invalid-token',
  ExpiredToken = 'expired-token',
  PermissionDenied = 'permission-denied',
  SessionExpired = 'session-expired',
}
